version: '3.7'

volumes:
  steamprice_db_volume:
    external: true
  redis:

services:
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      args:
        - WORK_DIR=/var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - steamprice_db_volume:/var/lib/postgresql/data/
  rds:
    image: redis:5
    volumes:
      - redis:/data
  composer:
    image: composer:1
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
  echo:
    build: ./docker/echo
    ports:
      - 2053:2053
    depends_on:
      - rds
  horizon:
    build: ./docker/horizon
    volumes:
      - ./laravel:/var/www/laravel
  watcher:
    image: node:12-alpine
    command: npm run watch
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
    logging:
      options:
        max-size: "100M"
        max-file: "1"
