version: '3.7'

volumes:
  steamprice_db_volume:
  redis:

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/laravel:cached
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      args:
        - WORK_DIR=/var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
    ports:
    - 5432:5432
    volumes:
      - steamprice_db_volume:/var/lib/postgresql/data/
  rds:
    image: redis:5
    volumes:
      - redis:/data
  composer:
    image: composer:1
    command: composer install --ignore-platform-reqs
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
  echo:
    build: ./docker/echo
    ports:
      - 2053:2053
    depends_on:
      - rds
  horizon:
    build: ./docker/horizon
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - rds
  watcher:
    image: node:12-alpine
    command: [sh, -c, "npm i && npm run watch"]
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
    logging:
      options:
        max-size: "100M"
        max-file: "1"
